# Generated by Django 2.2.6 on 2019-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('code', models.CharField(default='', max_length=10, unique=True)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
